env: 7dof-defend
agent:
    policy: td3-defend               
    seed: 0              
    start_timesteps: 2e3
    eval_freq: 2000
    max_timesteps: 5e7
    expl_noise: 0.1            
    batch_size: 256
    discount: 0.99             
    tau: 0.05
    policy_noise: 0.2             
    noise_clip: 0.5              
    policy_freq: 2       
    max_episode_steps: 500
    save_model: True     
    load_model: ""                             
    # dump_dir : /run/media/luke/Data/uni/SS2023/DL Lab/Project/qualifying/V3/td3
    dump_dir: ./defend
    file_name : ${agent.policy}_${env}_${agent.seed}