anneal_lr: true
clip_coef: 0.2
clip_vloss: true
cuda: true
ent_coef: 0.0
env_id: 3dof-hit
exp_name: train_ppo
gae_lambda: 0.95
gamma: 0.99
learning_rate: 0.0003
max_grad_norm: 0.5
norm_adv: true
num_envs: 1
num_minibatches: 8
num_steps: 256
seed: 1
target_kl: null
torch_deterministic: true
total_timesteps: 1000
update_epochs: 10
vf_coef: 0.5
