env: 7dof-hit
agent:
    policy: sac-hit              
    seed: 0              
    start_timesteps: 1000
    eval_freq: 3e3
    max_timesteps: 5e7     
    batch_size: 256
    discount: 0.99             
    tau: 0.005
    critic_lr: 3e-4
    actor_lr: 3e-4
    alpha_lr: 3e-4
    update_interval: 1    
    target_update_interval: 1 
    max_episode_steps: 500
    save_model: True     
    load_model: ""                             
    dump_dir : ./hit
    file_name : ${agent.policy}_${env}_${agent.seed}